ant:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  # OLD p: 20k d:10

  j_1_f_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_1_f_l
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_2_f_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_2_f_l
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_3_f_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_3_f_l
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_1_f_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_1_f_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_2_f_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_2_f_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_3_f_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_3_f_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_1_m_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_1_m_l
    pid: {p: 25000.0, i: 0.01, d: 10.0} 

  j_2_m_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_2_m_l
    pid: {p: 25000.0, i: 0.01, d: 10.0} 
    
  j_3_m_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_3_m_l
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_1_m_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_1_m_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_2_m_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_2_m_r
    pid: {p: 25000.0, i: 0.01, d: 10.0} 

  j_3_m_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_3_m_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_1_r_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_1_r_l
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_2_r_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_2_r_l
    pid: {p: 25000.0, i: 0.01, d: 10.0} 

  j_3_r_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_3_r_l
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_1_r_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_1_r_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_2_r_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_2_r_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}

  j_3_r_r_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_3_r_r
    pid: {p: 25000.0, i: 0.01, d: 10.0}